### PR TITLE
Updated multimeter to display negative voltages

### PR DESCRIPTION
**Pull request by dougmartin**
Added tracking of actual value along with existing absolute value in
the multimeter component.  The absolute value is still used as is in
the code with the actual value providing the sign before the display
is updated.

A small change was also needed to allow both the HV and negative sign
to display at the same time.  If both need to display the second blank
space is used for the sign, eg 'h 3 0 0' becomes 'h-3 0 0'.

### CODE REVIEW

**Comment by sfentress** [comment]
Did you test this out on the Simple DC Circuit example? The meter should read negative when you're in Voltage mode and you swap the probes.

When I test it, I don't see a negative sign.

I think that the problem is in multimeter.js:84: `drop = v1.subtract(v2).magnitude;`

A complex number's magnitude is always positive.

**Comment by dougmartin** [comment]
No, I tested it by adding debug code to force the value being set on the multimeter to be negative.  I thought the issue was the multimeter storing the input as an absolute value and not the input always being positive.  I'll update the code.

**Comment by sfentress** [comment]
>  I thought the issue was the multimeter storing the input as an absolute value and not the input always being positive.

I think it was both ;)

**Comment by dougmartin** [comment]
Ok - I updated the voltage calculation code for DC voltages.

**Comment by dougmartin** [comment]
I also tested it with the Simple DC Circuit example.

**Comment by sfentress** [comment]
Looks good!

**Comment by sfentress** [comment]
Released version 0.0.2 with this change.

The released version can be seen working at http://concord-consortium.github.io/breadboard/simple-dc-circuit.html

**Comment by phrwtz** [comment]
Jumped in late here. Good work, all. (Now I'm going to test my newfound
Github "expertise" to look over your shoulder!)

Paul

Paul Horwitz
The Concord Consortium
25 Love Lane
Concord, MA  01742

978-405-3223 (office)
978-369-4935 (home)
978-505-5401 (cell)
978-405-2078 (fax)

"Lead us not into temptation – just tell us where it is, we'll find it."

```
        Sam Levenson
```

**Pull request merged**
